workflows:
  android-apk:
    name: JNL Studio Booth APK Build

    max_build_duration: 60

    environment:
      node: latest
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          npm run build:android

    artifacts:
      - android/app/build/outputs/apk/**/*.apk
